services:
    db:
        image: mongo
        volumes:
            - /root/www/db/db:/data/db
            - /root/www/db/configdb:/data/configdb
        container_name: db
        restart: always

    www:
        build: .
        ports:
            - "127.0.0.1:8080:8080"
        volumes:
            - /root/www/logs:/www/logs
            - /root/www/public:/www/public
        links:
            - db
        depends_on:
            - db
        container_name: www
        restart: always

    nginx:
        image: nginx
        ports:
            - "9527:9527"
            - "8989:8989"
        volumes:
            - /root/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /root/nginx/ssl:/root/ssl:ro
            - /root/nginx/logs:/etc/nginx/logs
        links:
            - www
        depends_on:
            - www
        container_name: nginx
        restart: always
